import React, {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ShieldCheck,LayoutDashboard,ScanLine,History,ArrowUpRight,UploadCloud,ImagePlus,ChevronRight,Activity,Trash2,Download,Menu,X,CheckCircle2} from 'lucide-react';
import {validateFile,demoResult,validateResult} from './detection';
import './style.css';

function App(){
 const [page,setPage]=useState('Overview'),[mobile,setMobile]=useState(false),[mode,setMode]=useState('demo'),[health,setHealth]=useState('checking'),[file,setFile]=useState(null),[preview,setPreview]=useState(''),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[drag,setDrag]=useState(false),[overlay,setOverlay]=useState(true);
 const [records,setRecords]=useState(()=>{try{return JSON.parse(localStorage.getItem('bridgeguard-history')||'[]').filter(r=>r&&typeof r.name==='string'&&Number.isFinite(r.coverage)).slice(0,50)}catch{return []}});
 const input=useRef(), upload=useRef(), active=useRef(true);
 useEffect(()=>{active.current=true;return()=>{active.current=false}},[]);
 useEffect(()=>{const c=new AbortController();fetch('/api/health',{signal:c.signal}).then(r=>r.ok?r.json():Promise.reject()).then(d=>setHealth(d.model_ready?'ready':'missing')).catch(()=>setHealth('offline'));return()=>c.abort()},[]);
 useEffect(()=>{try{localStorage.setItem('bridgeguard-history',JSON.stringify(records))}catch{setError('Browser storage is full. History will last only for this session.')}},[records]);
 useEffect(()=>{if(!file){setPreview('');return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
 function choose(f){if(!f||busy)return;const message=validateFile(f);setError(message);if(!message){setFile(f);setResult(null)}}
 async function analyze(){if(!file||busy)return;setBusy(true);setError('');setResult(null);try{let data;if(mode==='demo'){await new Promise(r=>setTimeout(r,650));data=demoResult()}else{const body=new FormData();body.append('file',file);const response=await fetch('/api/detect',{method:'POST',body,signal:AbortSignal.timeout(60000)});if(!response.ok){let message='Detection failed. Check the API and model weights.';try{message=(await response.json()).detail||message}catch{}throw new Error(message)}data=validateResult(await response.json())}if(!active.current)return;setResult(data);setRecords(rows=>[{...data,mask:undefined,id:crypto.randomUUID(),name:file.name,date:new Date().toISOString()},...rows].slice(0,50))}catch(e){if(active.current)setError(e.name==='TimeoutError'?'Detection timed out. Please retry.':e.message)}finally{if(active.current)setBusy(false)}}
 function exportHistory(){const blob=new Blob([JSON.stringify(records,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='bridgeguard-inspections.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function navigate(p){setPage(p);setMobile(false);if(p==='New inspection')setTimeout(()=>upload.current?.scrollIntoView({behavior:'smooth'}),50)}
 const real=records.filter(r=>!r.demo),high=real.filter(r=>r.severity==='High').length;
 return <div className="app"><aside className={mobile?'sidebar open':'sidebar'}><a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('Overview')}}><span className="brand-icon"><ShieldCheck size={26}/></span>BridgeGuard<span className="brand-dot">®</span></a><div className="workspace"><span className="workspace-icon">BG</span><div>Inspection workspace<small>Bridge corrosion detection</small></div></div><div className="nav-label">WORKSPACE</div><nav>{[['Overview',LayoutDashboard],['New inspection',ScanLine],['Inspection history',History]].map(([p,Icon])=><button key={p} className={page===p?'nav-item selected':'nav-item'} onClick={()=>navigate(p)}><Icon size={19}/>{p}{p==='Inspection history'&&<span className="nav-count">{records.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="model-card"><Activity size={20}/><strong>Built for a closer look.</strong><p>Turn bridge imagery into actionable inspection records.</p><span>U-Net segmentation <ArrowUpRight size={14}/></span></div><div className="profile"><span>IN</span><div>Inspector<small>Local workspace</small></div><CheckCircle2 size={17}/></div></div></aside>
 {mobile&&<button className="backdrop" aria-label="Close navigation" onClick={()=>setMobile(false)}/>}
 <main><header><div className="breadcrumb"><button className="mobile-toggle" aria-label="Open navigation" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button>Workspace <ChevronRight size={14}/><b>{page}</b></div><span className={'status '+(health==='ready'?'ready':'')}><i/>{health==='ready'?'Model connected':health==='checking'?'Checking model…':health==='missing'?'Model weights needed':'API offline'}</span></header>
 <div className="content"><div className="page-heading"><div><div className="eyebrow">BRIDGE HEALTH, IN FOCUS</div><h1>{page==='Inspection history'?'Inspection history':'A clearer view of every bridge.'}</h1><p>{page==='Inspection history'?'Review your locally saved inspection measurements.':'Inspect surface corrosion. Understand the extent. Plan your next step.'}</p></div><button className="primary" onClick={()=>navigate('New inspection')}><ScanLine size={17}/> New inspection</button></div>
 {page!=='Inspection history'&&<><section className="hero"><div className="hero-copy"><span className="pill">IMAGE-BASED INSPECTION</span><h2>Small details.<br/>Stronger decisions.</h2><p>Bring corrosion into focus with pixel-level surface analysis.</p><button onClick={()=>upload.current?.scrollIntoView({behavior:'smooth'})}>Start an inspection <ArrowUpRight size={17}/></button></div><div className="bridge-art" aria-hidden="true"><div className="bridge-grid"/><svg viewBox="0 0 620 230"><path d="M0 173H620M110 175V42M470 175V42M95 43H125M455 43H485M110 53Q290 220 470 53M0 110Q55 102 110 53M470 53Q545 109 620 115"/><path className="cables" d="M145 82V173M185 110V173M225 131V173M265 145V173M305 148V173M345 140V173M385 122V173M425 94V173M35 105V173M75 84V173M515 86V173M560 107V173"/></svg><span className="scan-tag"><span/> SURFACE INTELLIGENCE</span></div></section>
 <section className="stats"><Stat label="Completed inspections" value={real.length.toString().padStart(2,'0')} note="Model analyses saved locally" icon={ScanLine}/><Stat label="High coverage findings" value={high.toString().padStart(2,'0')} note="At least 25% of image area" icon={Activity}/><Stat label="Demo inspections" value={(records.length-real.length).toString().padStart(2,'0')} note="Illustrative results only" icon={ImagePlus}/></section>
 <section className="inspection-grid" ref={upload}><div className="panel"><div className="panel-heading"><div><h3>New inspection</h3><p>Upload a clear photo of the bridge surface.</p></div><span className="step">01 / UPLOAD</span></div><div className="mode-row"><label htmlFor="mode">Analysis mode</label><select id="mode" value={mode} disabled={busy} onChange={e=>{setMode(e.target.value);setResult(null);setError('')}}><option value="demo">Demo · illustrative results</option><option value="model">Trained U-Net model</option></select></div><div className={'dropzone '+(drag?'drag':'')} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);choose(e.dataTransfer.files[0])}}>{preview?<><img className="preview" src={preview} alt="Selected bridge surface" onError={()=>{setError('This image could not be decoded. Choose another image.');setFile(null)}}/><button className="replace" disabled={busy} onClick={()=>input.current.click()}>Change image</button></>:<><div className="upload-icon"><UploadCloud size={29}/></div><h4>Drop your image here</h4><p>or <button className="text-button" onClick={()=>input.current.click()}>browse files</button></p><small>JPG, PNG or WebP · up to 10 MB</small></>}<input ref={input} type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={e=>{choose(e.target.files[0]);e.target.value=''}}/></div>{file&&<div className="file-info"><ImagePlus size={16}/><span>{file.name}</span><small>{(file.size/1024/1024).toFixed(2)} MB</small></div>}<div className="notice">{mode==='demo'?'Demo uses a fixed example measurement. It does not analyze your image.':'Requires the local API and trained weights from your notebook.'}</div>{error&&<p className="error" role="alert">{error}</p>}<button className="primary analyze" disabled={!file||busy} onClick={analyze}><ScanLine size={18}/>{busy?'Analyzing image…':'Analyze surface'}<ArrowUpRight size={17}/></button></div>
 <div className="panel result-panel"><div className="panel-heading"><div><h3>Detection results</h3><p>Surface coverage and segmentation.</p></div><span className="step">02 / REVIEW</span></div>{!result?<div className="empty-result" aria-live="polite"><div className="target-icon"><ScanLine size={38}/></div><h4>{busy?'Inspecting your image':'Ready when you are'}</h4><p>{busy?'Your results will appear here.':'Upload an image and run an inspection to explore the results.'}</p><span>UPLOAD <ChevronRight size={12}/> ANALYZE <ChevronRight size={12}/> REVIEW</span></div>:<div aria-live="polite">{result.demo&&<div className="demo-banner">DEMO RESULT · NOT AN IMAGE MEASUREMENT</div>}<div className="measurement"><div><small>Corrosion coverage</small><strong>{result.coverage.toFixed(1)}<span>%</span></strong></div><span className={'badge '+result.severity.toLowerCase()}>{result.severity} coverage</span></div><div className="meter"><i style={{width:`${result.coverage}%`}}/></div>{result.mask&&<><label className="overlay-toggle"><input type="checkbox" checked={overlay} onChange={e=>setOverlay(e.target.checked)}/> Show segmentation overlay</label><div className="mask-view"><img src={preview} alt="Inspected surface"/>{overlay&&<img className="mask" src={result.mask} alt="Predicted corrosion mask"/>}</div></>}<p className="result-description">{result.demo?'This example shows how a moderate coverage result appears. Switch to the trained model for image analysis.':'Coverage is the percentage of resized image pixels classified as corrosion. It does not measure structural condition.'}</p><div className="legend"><span>Low &lt;10%</span><span>Moderate 10–25%</span><span>High ≥25%</span></div><div className="saved"><CheckCircle2 size={16}/> Saved to local inspection history</div></div>}</div></section></>}
 <section className="panel history-panel"><div className="panel-heading"><div><h3>{page==='Inspection history'?'All inspections':'Recent inspections'}</h3><p>Your latest surface analysis, in one place.</p></div><button className="subtle" disabled={!records.length} onClick={exportHistory}><Download size={15}/> Export</button></div>{!records.length?<div className="history-empty"><History size={23}/><span>No inspections yet. Your first result will appear here.</span></div>:<div className="table-wrap"><table><thead><tr><th>IMAGE</th><th>DATE</th><th>COVERAGE</th><th>LEVEL</th><th>SOURCE</th><th/></tr></thead><tbody>{(page==='Inspection history'?records:records.slice(0,5)).map(r=><tr key={r.id}><td><div className="table-name"><span><ImagePlus size={17}/></span>{r.name}</div></td><td>{new Date(r.date).toLocaleString()}</td><td>{r.coverage.toFixed(1)}%</td><td><span className={'badge '+r.severity.toLowerCase()}>{r.severity}</span></td><td>{r.demo?'Demo':'U-Net'}</td><td><button className="delete" aria-label={`Delete inspection ${r.name}`} onClick={()=>setRecords(rows=>rows.filter(x=>x.id!==r.id))}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>}</section><footer><ShieldCheck size={14}/> BridgeGuard · Surface insights for informed inspections<span>Measurements support professional review.</span></footer></div></main></div>
}
function Stat({label,value,note,icon:Icon}){return <div className="stat"><div><span>{label}</span><Icon size={18}/></div><strong>{value}</strong><small>{note}</small></div>}
createRoot(document.getElementById('root')).render(<App/>);
